name: "Issue Refs Parser"
description: "Parse linked references from a string such as a issue or pull request body."
author: "FujiHaruka"
inputs:
  body:
    description: "Raw input string to be parsed"
    required: true
  self_slug:
    description: "Slug string of the repository where the action runs"
outputs:
  refs:
    description: "Referenced issue numbers in the same repository"
  external_refs:
    description: "Referenced issue refs in different repositories"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "hash"
  color: "white"
