on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install
        run: npm install
      - name: Test
        run: npm test
